name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.22
          - 1.23
          - stable

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: make build
